### ISSUE TITLE
Wrong language codes

### ISSUE THREAD

**Issue by burningtree** [niclaz/Archive-of-Bitcoin-Whitepaper-translations#2]
The generally accepted standard for designating languages is ISO 639-2, but this repository uses some weird coding.

https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes

For example:
- czech language: `cs` (mislabeled as `cz`)
- japan language: `ja` (mislabeled as `jp`)
- greek language: `el` (mislabeled as `gr`)
- swedish language: `sv` (mislabeled as `se`)

Given the codes, I assume someone is confusing national domain and country codes with language codes - they are not the same. I haven't checked all the codes, most seem correct (like Estonian `et`, where Estonian country code & domain is `ee`).

**Comment by niclaz** [comment]
Thanks for correcting it Tree!

Yeah... I wasn't following ISO when naming the pdfs and some of them were collected already named as they were

Thanks for going through and finding these errors, happy to have them named better

**Comment by niclaz** [comment]
I made the above edits to the main branch of the archive

Thanks tree

**Comment by EuJinnLucaShow** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
rev3z, @hczhu, @liujiao111, @N1ghtu, @arjunshibu, @afzaanhakim, @royds4, @lonelyWarrior127, @GiovaLomba, @vangogh-ken, @Sunchao1996, @digitalbase, @duongptryu, @Axhat, @pp0001, @kevinnguyenai, @jagveer-gandhi, @kohasummons, @ryanlj77, @eliashussary
